apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - log-output-config.yaml
  - route.yaml
  - ../../ping-pong/manifests/