apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong-app
  namespace: exercises
spec:
  template:
    spec:
      containers:
        - image: sakuheinonen/ping-pong:5.7.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: APP_PORT
              value: "8080"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_DB
              value: "pingpong"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
