apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - rollout.yaml
  - analysis-template.yaml
  - service.yaml
  - postgres-config.yaml
  - postgres-db.yaml
  - postgres-service.yaml