apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: exercises
data:
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_DB: "pingpong"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"

