apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-app
  namespace: exercises
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 10s
        - setWeight: 100
        - analysis:
            templates:
              - templateName: ping-pong-cpu-guard
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: ping-pong-app
          image: sakuheinonen/ping-pong:4.4
          env:
            - name: PORT
              value: "3050"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /db-health
              port: 3050
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
