apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercises
spec:
  selector:
    app:
      ping-pong-app
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3050
  type: ClusterIP
  