apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      namespace: exercises
      name: log-output
      labels:
        app: log-output
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: log-output
          image: sakuheinonen/log-output:5.3.1
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: log-output-config
            - name: PING_PONG_URL
              valueFrom:
                configMapKeyRef:
                  key: PING_PONG_URL
                  name: log-output-config
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE
                  name: log-output-config
            - name: GREETER_URL
              valueFrom:
                configMapKeyRef:
                  key: GREETER_URL
                  name: log-output-config
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/files
              readOnly: true

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -sf http://ping-pong-svc:3080/pings"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2

      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
